### ISSUE TITLE
it is not working with grid layout

### ISSUE THREAD

**Issue by mrunal7761** [shayanpourvatan/PaginationHandler#1]
i tried using it with grid layout,but it is not working with that.

**Comment by shayanpourvatan** [comment]
What is your mean about not working with that? could you clarify your problem.
Please post related code too.

**Comment by mrunal7761** [comment]
when i  tried to implement it with grid layout,it doesn't respond well as expected.
according to your sample code,i tried to use it,but unfortunately no desirable outcome. sorry if you find is as silly or minor mistake.

**Comment by shayanpourvatan** [comment]
no, I don't think it silly, I glad to help you if I can.
you must post your code that I can help you.
